### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by 0kok0** [status-im/status-security#9]

**Comment by 0kok0** [comment]
With `window.location = "https://google.com/generate_204"` [this](https://github.com/status-im/status-react/blob/68f0a02cbcfc32151a9e8dc87e5f9c27c449dcd0/src/status_im/ui/screens/browser/views.cljs#L130) code path triggers the change in the address bar. 

The induced navigation state change:

![image](https://user-images.githubusercontent.com/61156799/80234720-ec6c8380-8658-11ea-8322-5113c8e72c20.png)

**Comment by 0kok0** [comment]
Further context: 
Webview's  `:on-error` does not properly propagate different errors, including ssl errors. We use [:on-navigation-state-change](react/blob/68f0a02cbcfc32151a9e8dc87e5f9c27c449dcd0/src/status_im/ui/screens/browser/views.cljs#L130) to set the new URL before errors are caught.

**Comment by siphiuel** [comment]
Some notes:
1. WebView's error handling. We should use `onHttpError` instead (https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onhttperror). This will help catch HTTP errors.
2. `onNavigationStateChange` prop ([docs](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onnavigationstatechange). It's invoked twice for each navigation - when starting and finishing page load. Probably we can use then to check whether navigation changes are authentic (e.g. `title = url`).
